name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master  # Reemplaza 'main' con la rama que quieras usar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Reemplaza con la versión de .NET que estás usando

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the app
      run: dotnet build --configuration Release --no-restore

    - name: Publish the app
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish --no-build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: apikey-rotation-mvp-backend  # Reemplaza con el nombre de tu App Service
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
